# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: ElectroCat
  description: A Python toolkit for analyzing molecular and surface electrocatalysts in solvated and ion-rich environments
  homepage: https://www.skethirajan.com/ElectroCat/
  topics: electrocatalysis, electrochemistry, solvation, catalysts, interfaces, python, dft, atomistic-simulations, molecular-dynamics, materials-science
  private: false
  default_branch: main
  has_issues: true
  has_wiki: true
  has_projects: true
  has_downloads: true
  delete_branch_on_merge: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true  # Require PRs to be up-to-date before merging
        contexts:
          - Lint Commits
          - Lint PR Title
          - Mkdocs
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismiss_stale_reviews_when_new_commits_are_pushed: true
        require_last_push_approval: false
      restrictions:
        users:
          - skethirajan
        teams: []
        apps: []
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: true
      required_conversation_resolution: true

  - name: gh-pages
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions:
        users: []
        teams: []
        apps: []
      allow_force_pushes: true  # Required for mkdocs gh-deploy
      allow_deletions: false
