repo_url: https://github.com/skethirajan/ElectroCat
site_author: Sudheesh Kumar Ethirajan
site_description: >-
  ElectroCat: A Python toolkit for analyzing molecular and surface
  electrocatalysts in solvated and ion-rich environments.
site_name: ElectroCat
site_url: https://skethirajan.github.io/ecat/

nav:
  - Home: index.md
  - Installation Guide 🔧: user/install.md
  - User Guide 🧠:
      - Getting Started: user/intro.md
      - Examples: user/examples.md
  - Code Documentation 📖: reference/
  - Developer Guide 🤝:
      - Contributing: dev/contributing.md
      - Documentation: dev/docs.md
  - About 📜:
      - Changelog: about/changelog.md
      # - Citation: about/citation.md
      - Acknowledgements: about/acknowledgements.md
      - License: about/license.md

theme:
  name: material
  favicon: assets/ecat_icon.png
  logo: assets/ecat_icon.png
  palette:
    primary: orange
    scheme: slate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://wiki.fysik.dtu.dk/ase/objects.inv
            - https://pymatgen.org/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: list
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_if_no_docstring: true

  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

edit_uri: blob/main/docs/
extra:
  social:
    - icon: fontawesome/brands/web-awesome
      link: https://www.skethirajan.com
