name: Lint Commits

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for `--from / --to` to work properly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install commitlint
        run: npm install

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate last 20 commits from current with commitlint
        if: github.event_name == 'push'
        run: |
          if git rev-parse HEAD~20 >/dev/null 2>&1; then
            npx commitlint --from HEAD~20 --to HEAD --verbose
          else
            npx commitlint --from $(git rev-list --max-parents=0 HEAD) --to HEAD --verbose
          fi

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
            --from "${{ github.event.pull_request.base.sha }}" \
            --to "${{ github.event.pull_request.head.sha }}" \
            --verbose
